name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '16.x'

      - name: Build
        run: |
          npm install -g firebase-tools
          npm install
          npm run build

      - name: Prepare
        run: |
          mv src/.vuepress/dist public
          cd functions
          npm install
          cd ..

      - name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}'

      - name: Deploy
        run: |
          firebase deploy

